# Generated by Django 4.0.5 on 2022-06-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0002_alter_user_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_description', models.TextField(max_length=200)),
                ('course_content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='educator_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.course_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.user_details')),
            ],
        ),
    ]
